### ISSUE TITLE
Consider maintaining a homebrew tap

### ISSUE THREAD

**Issue by designorant** [ONSdigital/dp-cli#93]
I noticed the [onboarding](https://github.com/ONSdigital/dp/blob/main/guides/GETTING_STARTED.md) is aimed at macOS users, and often mentions homebrew.  `dp-cli` would be a great candidate for an in-house [homebrew tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). This would simplify both the installation (including dependencies) and update processes.

Further info:
- https://docs.brew.sh/Taps
- https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

With the 227 dp repositories I've just been subscribed to right off the bat as part of the digitalpublishing team, there's likely more tools/software that could be distributed/managed via a tap.

**Comment by morses-code** [comment]
Great idea, I've recently been looking into making sure the tool shows users if the version they are running is out of date. Never thought of using brew, I'm going to take a look into this when I can.

**Comment by gedge** [comment]
https://github.com/ONSdigital/dp-cli/pull/110
